// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCandidate(ctx context.Context, arg CreateCandidateParams) error
	CreateCompany(ctx context.Context, description sql.NullString) error
	CreateJob(ctx context.Context, arg CreateJobParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteCandidate(ctx context.Context, id uuid.UUID) error
	DeleteCompany(ctx context.Context, id uuid.UUID) error
	DeleteJob(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetCandidate(ctx context.Context, id uuid.UUID) (Candidate, error)
	GetCompany(ctx context.Context, id uuid.UUID) (Company, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	ListCandidates(ctx context.Context) ([]Candidate, error)
	ListCompanies(ctx context.Context) ([]Company, error)
	ListJobs(ctx context.Context) ([]Job, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateCandidate(ctx context.Context, id uuid.UUID) error
	UpdateCompany(ctx context.Context, id uuid.UUID) error
	UpdateJob(ctx context.Context, arg UpdateJobParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
